export const AUTHTEST_API_CALL = 'AUTHTEST_API_CALL';
export const AUTHENTICATE_API_CALL = 'AUTHENTICATE_API_CALL';

export const BROWSER_ARTISTS_API_CALL = 'BROWSER_ARTISTS_API_CALL';
export const LIST_BROWSER_API_CALL = 'LIST_BROWSER_API_CALL';

export const SEARCH_SUGGESTIONS_API_CALL = 'SEARCH_SUGGESTIONS_API_CALL';

export const SETTINGS_UPDATE_TRIGGERED = 'SETTINGS_UPDATE_TRIGGERED';
