/** App actions */
export const APP_HIDE_SPINNER = 'APP_HIDE_SPINNER';

/** Browser actions */
export const BROWSER_ARTISTS_REQUESTED = 'BROWSER_ARTISTS_REQUESTED';
export const BROWSER_ALBUMS_REQUESTED = 'BROWSER_ALBUMS_REQUESTED';

export const BROWSER_ARTISTS_FETCHED = 'BROWSER_ARTISTS_FETCHED';
export const BROWSER_ALBUMS_FETCHED = 'BROWSER_ALBUMS_FETCHED';

/** Player actions */
export const PLAYER_TRACK_ADDED = 'PLAYER_TRACK_ADDED';
export const PLAYER_PAUSE_TOGGLED = 'PLAYER_PAUSE_TOGGLED';

