/** App actions */
export const APP_HIDE_SPINNER = 'APP_HIDE_SPINNER';

/** Browser actions */
export const BROWSER_ARTISTS_REQUESTED = 'BROWSER_ARTISTS_REQUESTED';
export const BROWSER_ALBUMS_REQUESTED = 'BROWSER_ALBUMS_REQUESTED';

export const BROWSER_ARTISTS_FETCHED = 'BROWSER_ARTISTS_FETCHED';
export const BROWSER_ALBUMS_FETCHED = 'BROWSER_ALBUMS_FETCHED';

export const BROWSER_ARTIST_SELECTED = 'BROWSER_ARTIST_SELECTED';
export const BROWSER_ALBUM_SELECTED = 'BROWSER_ALBUM_SELECTED';

/** List actions */
export const LIST_ARTIST_SELECTED = 'LIST_ARTIST_SELECTED';
export const LIST_ALBUM_SELECTED = 'LIST_ALBUM_SELECTED';

/** Player actions */
export const PLAYER_TRACK_ADDED = 'PLAYER_TRACK_ADDED';
export const PLAYER_TRACK_PLAYED = 'PLAYER_TRACK_PLAYED';
export const PLAYER_PAUSE_TOGGLED = 'PLAYER_PAUSE_TOGGLED';
export const PLAYER_CTRL_PREVIOUS_CLICKED = 'PLAYER_CTRL_PREVIOUS_CLICKED';
export const PLAYER_CTRL_NEXT_CLICKED = 'PLAYER_CTRL_NEXT_CLICKED';
export const PLAYER_POSITION_SEEKED = 'PLAYER_POSITION_SEEKED';

/** Audio actions */
export const AUDIO_STREAM_CANPLAY = 'AUDIO_STREAM_CANPLAY';
export const AUDIO_STREAM_BEGAN = 'AUDIO_STREAM_BEGAN';
export const AUDIO_DURATION_SET = 'AUDIO_DURATION_SET';
export const AUDIO_ERROR_OCCURRED = 'AUDIO_ERROR_OCCURRED';
export const AUDIO_STREAM_PROGRESSED = 'AUDIO_STREAM_PROGRESSED';
export const AUDIO_TIME_UPDATED = 'AUDIO_TIME_UPDATED';
export const AUDIO_VOLUME_SET = 'AUDIO_VOLUME_SET';

