export const BROWSER_ARTISTS_API_CALL = 'BROWSER_ARTISTS_API_CALL';
export const BROWSER_ALBUMS_API_CALL = 'BROWSER_ALBUMS_API_CALL';

export const LIST_ARTIST_API_CALL = 'LIST_ARTIST_API_CALL';
export const LIST_ALBUM_API_CALL = 'LIST_ALBUM_API_CALL';
